### ISSUE TITLE
Use latest through2 (and maybe others)

### ISSUE THREAD

**Issue by victornoel** [mafintosh/peek-stream#3]
Hi,

I tried using `gunzip-maybe` (which depends on `peek-stream` as you must know) and faced some strange problems (see https://github.com/yarnpkg/yarn/pull/2971#issuecomment-288576714).

The source of the problem is most certainly because the version of readable-stream is *really* old and this dependency comes from `through2`, itself of a very old version in `peek-stream`.
I tried to force the dependency of `through2` to 2.0.3 and everything worked like a charm.

Could we get `peek-stream` (and then `gunzip-maybe` :) improved to use up-to-date dependencies?

Thanks!

**Comment by victornoel** [comment]
@mafintosh ping? :)

**Comment by mafintosh** [comment]
All deps bumped in 1.1.2 - gunzip-maybe automatically gets this if you reinstall

**Comment by victornoel** [comment]
great thanks!
